name: "Matrix Test Strategy"
on:
  # Manual trigger
  workflow_dispatch:


jobs:
  matrix:
    name:   ${{matrix.runner}} - ${{ matrix.environment }}
    runs-on: [ '${{ matrix.runner }}']
    strategy:
      max-parallel: 1
      matrix:
         include:
           - environment: dev-tst
             runner: ubuntu-latest
           - environment: production
             runner: windows-latest
